package com.capgemini.farmers;

import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Referrals extends CallCenterTest {
	private static String str="Referrals";
	private static Logger logger = LoggerFactory.getLogger(Referrals.class);
	
	@Test
	public void validate() {
		Map<String,String> map=getProperties("validateReferrals");
		startTime=System.nanoTime();
		initChrome();
		webDriver.navigate().to(map.get("urlreferrals"));
		//logger.info(urlreferrals);
		screenshot(str);
		webDriver.findElement(By.xpath("/html/body/div[2]/ul/li[2]/a")).click();
		logger.info("Clerical - CAHI tab loaded successfully");

		screenshot(str); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[2]/div[1]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("CS Letter Validated successfully"); 
		sleep(5);
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
        screenshot(str);
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[2]/div[2]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("ID Card Order Request Validated successfully");  
		sleep(5);
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
        screenshot(str);
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[2]/div[3]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Image Request Validated successfully");
		sleep(5);
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
        screenshot(str);

		webDriver.findElement(By.xpath("/html/body/div[2]/ul/li[3]/a")).click();
		logger.info("Customer Service - CAHI tab loaded successfully");
		screenshot(str);

		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[3]/div[1]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("CA - Multi-Day Change: AutoPay Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
        screenshot(str);
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[3]/div[2]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("CA - Multi-Day Change: Operator Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
        screenshot(str);
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[3]/div[3]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("CA - Multi-Day Change: Other Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[3]/div[4]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("CA - Multi-Day Change: Vehicle Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[3]/div[5]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("HI - Multi-Day Change: AutoPay Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[3]/div[6]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("HI - Multi-Day Change: Operator Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[3]/div[7]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("HI - Multi-Day Change: Other Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[3]/div[8]/a[1]")).click();
		sleep(5);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("HI - Multi-Day Change: Vehicle Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();

		webDriver.findElement(By.xpath("/html/body/div[2]/ul/li[4]/a")).click();
		screenshot(str);
		logger.info("Financial Responsibility - CAHI tab loaded successfully");

		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[4]/div[1]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("MVR CLUE - In Discovery Validated successfully"); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[4]/div[2]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("SR21 Validated successfully"); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[4]/div[3]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("SR22 - CA Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[4]/div[4]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("SR22 - HI Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();

		webDriver.findElement(By.xpath("/html/body/div[2]/ul/li[5]/a")).click();
		screenshot(str);
		logger.info("Premium Accounting - CAHI tab loaded successfully");

		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[1]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("DRC - Check Requisition Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[2]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("DRC - Statement of Account Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[3]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - ACH EFT - New Setup Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[4]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - ACH EFT - Terminate Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[5]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("PSP - ACH EFT - Update Existing Validated successfully"); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[6]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - ACH Payment Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[7]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Change in Bill Plan Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[8]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Change in Effective Date Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[9]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Check Requisition Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[10]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - COVID Due Date Adjustment Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[11]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("PSP - Credit Card EFT - New Setup Validated successfully"); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[12]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Credit Card EFT - Terminate Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[13]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("PSP - Credit Card EFT - Update Existing Validated successfully"); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[14]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("PSP - Credit Card Payment Validated successfully"); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[15]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Credit Card Reversal Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[16]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Debit/Credit Card Release Bank Hold Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[17]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Encoding Error Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[18]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Hold Credit Refund Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[19]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Misapplied Payment Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[20]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Policy Fee Write Off Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[21]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Premium Increase/Decrease Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[22]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Reinstatement with Lapse Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[23]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Reinstatement Without Lapse Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[24]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Statement of Account Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[5]/div[25]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP - Transfer Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();


		webDriver.findElement(By.xpath("/html/body/div[2]/ul/li[6]/a")).click();
		screenshot(str);
		logger.info("Regulatory Reporting tab loaded successfully");

		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[6]/div[1]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("DMV Filing Request - EFile States Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[6]/div[2]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("DMV Filing Request - Non-EFile States Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();

		webDriver.findElement(By.xpath("/html/body/div[2]/ul/li[7]/a")).click();
		screenshot(str);
		logger.info("Special Services tab loaded successfully");

		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[7]/div[1]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Escalated Situation Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[7]/div[2]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Executive Complaint Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[7]/div[3]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Technical Support Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();

		webDriver.findElement(By.xpath("/html/body/div[2]/ul/li[8]/a")).click();
		screenshot(str);
		logger.info("Underwriting - CAHI tab loaded successfully");

		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[8]/div[1]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Claims Request Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[8]/div[2]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("Customization Validated successfully"); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[8]/div[3]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Disputed Activity Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[8]/div[4]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Named Driver Exclusion Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[8]/div[5]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str);
		logger.info("Operator Related Validated successfully"); 
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[8]/div[6]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Vehicle Related Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();

		webDriver.findElement(By.xpath("/html/body/div[2]/ul/li[9]/a")).click();
		screenshot(str);
		logger.info("Universal Help Desk - CAHI tab loaded successfully");

		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[9]/div[1]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("Error Report Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[9]/div[2]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP Followup - CA Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.findElement(By.xpath("/html/body/div[2]/div[1]/div[9]/div[3]/a[1]")).click();
		sleep(3);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		screenshot(str); 
		logger.info("PSP Followup - HI Validated successfully");
		webDriver.findElement(By.xpath("/html/body/div[2]/div[2]/form/div/div/div[2]/div[2]/fieldset/div[5]/button[2]")).click();
		webDriver.close();
		webDriver.quit();
	}
}
