package com.capgemini.farmers;

import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SupplementalDocuments extends CallCenterTest {
	private static String str="SupplementalDocuments";
	private static Logger logger = LoggerFactory.getLogger(SupplementalDocuments.class);
	
	@Test
	public void validate() {
		Map<String,String> map=getProperties("validateSD");
		startTime=System.nanoTime();
		initChrome();
		webDriver.navigate().to(map.get("urlSD"));
		screenshot(str);
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[1]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Anti-Theft Discount Verification Validated successfully");
        screenshot(str); 
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[2]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("AutoPay Manual Draft Letter Validated successfully");
		sleep(3);
        screenshot(str);
		webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[3]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Cancellation Insureds Request Letter Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[4]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Coverage Verification Letter Validated successfully");
		sleep(3);
        screenshot(str);
        //webDriver.navigate().to(map.get("urlSD"));
		//webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[5]/a")).click();
        //webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		//webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		//sleep(3);
        //screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[6]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Employer Additional Insured Letter Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[7]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Incorrect Premium Notice Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[8]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Motorhome and Trailer Rental Endorsement Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[9]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("No Contact Letter Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[10]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("No Loss Letter Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[11]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Payment Confirmation Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[12]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Policy Self-Service Registration Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[13]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Proof of Insurance Letter Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[14]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Refer A Good Friend Letter Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[15]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Refer A Good Friend Letter (Spanish) Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[16]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Sales Cancellation Letter Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[17]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Temporary NDE Waiver Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[18]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Thank You Letter Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[19]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("Thank You Letter (Spanish) Validated successfully");
		sleep(3);
        screenshot(str);
        webDriver.navigate().to(map.get("urlSD"));
		webDriver.findElement(By.xpath("/html/body/div/div/div/div/ul/li[20]/a")).click();
        webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[5]/div[1]/input")).sendKeys(map.get("policyno"));
		webDriver.findElement(By.xpath("/html/body/div/div/form/div/div/div/div/fieldset/div[6]/button[1]")).click();
		logger.info("UW Decision - Policy Remains Cancelled Validated successfully");
		sleep(3);
        screenshot(str);
		webDriver.close();
		webDriver.quit();
	}
}
